### ISSUE TITLE
Consolidate/Extract package updating/inserting functionality into new Service.

### ISSUE THREAD

**Issue by bforchhammer** [webflo/packagist#1]
- `Packagist\WebBundle\Package\BackgroundUpdater`
- `Packagist\WebBundle\Package\Upserter`
- `Packagist\WebBundle\Package\BackgroundUpsertConsumer`
- `Packagist\WebBundle\Package\BackgroundAdder`
- `Packagist\WebBundle\Command\UpdatePackagesCommand`

**Comment by webflo** [comment]
This issue was moved to drupal-composer/drupal-packagist#11
