### ISSUE TITLE
Drush version of extensions may be too restrictive

### ISSUE THREAD

**Issue by derhasi** [webflo/packagist#10]
When I look at [registry_rebuild](http://drupal-packagist.webflo.io/packages/drupal/registry_rebuild) and [drush_language](http://drupal-packagist.webflo.io/packages/drupal/drush_language), the version constraint for those extensions seem to be too restrictive, as this will not allow to have drush 7 (dev-master) fulfill the requirement.

**Comment by webflo** [comment]
The version constraints are correct but you need https://packagist.org/packages/drush/drush instead of the drush package definitions from our drupal-packagist. But drupal-packagist has a higher priority than packagist.org

**Comment by webflo** [comment]
Always require "drush/drush" instead of "drupal/drush"

**Comment by derhasi** [comment]
I know "drush/drush", but the given version constraint is too restrictive:  `drush/drush: 6.*` and that does not allow to install `dev-master`or `7.*`.

**Comment by derhasi** [comment]
Where is that drush version comming from. I cannot find code for that.

**Comment by derhasi** [comment]
For reference: the drush version is set in https://github.com/drupal-composer/drupal-parse-composer/blob/58ebd43f71f1f23bb96052fa0f95e2d6cfc09273/src/Project.php#L108

**Comment by webflo** [comment]
This issue was moved to drupal-composer/drupal-packagist#5
