### ISSUE TITLE
Stable release was not created (registry_rebuild)

### ISSUE THREAD

**Issue by derhasi** [webflo/packagist#12]
Currently only 1.\* releases are available for registry_rebuild, althoguh there is an up-to-date recommended 2.2 stable release.
- http://drupal-packagist.webflo.io/packages/drupal/registry_rebuild
- https://www.drupal.org/project/registry_rebuild

**Comment by webflo** [comment]
This issue was moved to drupal-composer/drupal-packagist#3

**Comment by webflo** [comment]
This issue was moved to drupal-composer/drupal-packagist#4
