### ISSUE TITLE
Change handling of sub-modules

### ISSUE THREAD

**Issue by bforchhammer** [webflo/packagist#2]
Ideas:
- Leave "provides" statement in `composer.json`
- Move submodule "requirements" into "suggest" section
- Add new `metapackage` entries for each sub module; add in/parse submodule dependencies and other information.

Related discussion:
- https://github.com/winmillwill/drupal-parse-composer/issues/4
- https://github.com/winmillwill/drupal-parse-composer/issues/6
- https://github.com/winmillwill/drupal-parse-composer/issues/8

**Comment by webflo** [comment]
Moved submodule "requirements" into "suggest" section in https://github.com/webflo/drupal-parse-composer/tree/submodule-dependencies

Some examples:
- http://drupal-packagist.webflo.io/packages/drupal/ctools
- http://drupal-packagist.webflo.io/packages/drupal/panels

**Comment by webflo** [comment]
This issue was moved to drupal-composer/drupal-packagist#10
