### ISSUE TITLE
Module panels_tabs missing

### ISSUE THREAD

**Issue by derhasi** [webflo/packagist#3]
Hi webflo, I just wanted to try to build drupal project containing `erpal_core` with a composer.json. But the build seems to fail, as your packagist does not hold information about `panels_tabs`
- Packagist: http://drupal-packagist.webflo.io/packages/drupal/panels_tabs
- Drupal.org: https://www.drupal.org/project/panels_tabs

**Comment by webflo** [comment]
Fixed added panels_tabs manually because panels_tabs was not automatically added because there is no d7 release.
