### ISSUE TITLE
7.?.x-dev notation for all branches

### ISSUE THREAD

**Issue by derhasi** [webflo/packagist#5]
On projects with more than one branch, only the latest one seems to get that special notation. For example see http://drupal-packagist.webflo.io/packages/drupal/master . The notation `7.2.x-dev` seems to be missing for that project.

In adition, I wonder if there is better composer/semver-like notation to use in general.

**Comment by webflo** [comment]
Hmmm, not sure what changed but 7.2.x-dev and 7.3.x-dev is visible on http://drupal-packagist.webflo.io/packages/drupal/master

**Comment by derhasi** [comment]
I guess you fixed something, while we where talking in IRC. Works for some time already.

**Comment by derhasi** [comment]
Maybe it was the change from https://github.com/webflo/packagist/commit/ee0c3a07bcf141cf12c31773f01e9d229bb821cf
