### ISSUE TITLE
Use "suggest" for dependencies of submodules

### ISSUE THREAD

**Issue by derhasi** [webflo/packagist#8]
When a module like `panels` is required a lot of dependencies are downloaded, although the core module does not necessarily need those.

[Composer.json can hold suggestions for other packages](https://getcomposer.org/doc/04-schema.md#suggest). This way we could provide information about those optional dependencies without the need of downloading all eventual dependencies of submodules.

Example for Panels:

``` json
{
  "require": {
    "drupal/ctools": "7.*" 
  },
  "suggest": {
    "drupal/i18n": "7.*",
    "drupal/i18n_string": "7.*",
    "drupal/i18n_translation": "7.*"
  }
}
```

**Comment by kasperg** [comment]
This seems to be a duplicate of #2 which also has references to other issues in `winmillwill/drupal-parse-composer` were this is discussed.

**Comment by webflo** [comment]
Updated the panels module. http://drupal-packagist.webflo.io/packages/drupal/panels

**Comment by derhasi** [comment]
Looks good. Also works for [rules](http://drupal-packagist.webflo.io/packages/drupal/rules).
